### ISSUE TITLE
O(n * m) complexity; O(n + m) should be instead

### ISSUE THREAD

**Issue by vitalk** [DmitryMantush/L_E#2]
https://github.com/DmitryMantush/L_E/blob/d7c19f813e66df00f9c5a8b59607063e3051e303/RoomStudent.py#L13

**Comment by DmitryMantush** [comment]
class Packer(DataProcessing):


    def pack(self):
        res = defaultdict(list)
        for el in self.data:
            res[el['room']].append(el)
        return res




def main():
    rooms = DataIn('rooms.json').load()
    students = DataIn('students.json').load()
    stud_by_rooms = Packer(students).pack()
    for room in rooms:
        room['students'] = stud_by_rooms[room['id']]
