### ISSUE TITLE
Please remove global variable usage

### ISSUE THREAD

**Issue by vitalk** [DmitryMantush/L_E#5]
https://github.com/DmitryMantush/L_E/blob/d7c19f813e66df00f9c5a8b59607063e3051e303/threading_mistake.py#L18

**Comment by DmitryMantush** [comment]
def main():
    a = 0
    with concurrent.futures.ThreadPoolExecutor() as tpe:
        results = [tpe.submit(function, 1000000) for _ in range(5)]
        for z in concurrent.futures.as_completed(results):
            a += z.result()
